notifications:
  email:
    on_success: change
    on_failure: change
sudo: false
language: python
python:
- 2.7
- 3.4
- 3.5
- 3.6
- 3.7
- 3.8
install:
- pip install -r requirements-dev.txt
- pip install -r requirements.txt
- pip install .
#deploy:
#  provider: pypi
#  user: ddaa
#  password:
#    secure: "h3TAswpjiwKRex+g0T87iW35r4BqaSmZ289sM8ZmSRgOSSZ0QiznEQJvCZPIL+1e7kPQqoC98o7ahJRa5SfTPX6+CNMEvwneUh/IvAuUCvBzYno/RTezP8YcGesGQm3ERssqv/NoS5weOFJu6CHjgM0POFBV6NDql+m4suXLQ2ndy3fArMYTP4FtyYIawXAgGoTyZ6shfvxZx57Q4sR+9TfK1kSCp3gJ9B2NEtYzGdanzSppK/gZoINmxuhJT53bib3SuLPcNJrsn8xZbfVZd4tD2ZW+0r+9zn46aX/hYfhOMC/QBhGS2cdcFDf5wlgmPTvQ6XsCvnIJgIpN+lgZACWmrkUMcH/PwUc3wYQaeG/QfrM7rF2/9M9XiCYEq8Zy6KhiJgdYrTaxC1lrMMeF9bSfLEm011oNhS0yxLN3uCkS/e+g96K3p/anjFdgT0hu8qBO7a1dGPMhNJmVJeZ0KVB4saU7EONwOA8EiRNZEpPwb7liiowYL/0cG2rtFfHPpEshf9TOmJUvsu4UqA8HRuUohzMravJMdXxhuqPrS3hSEncm29jzrtMtTIfY70cw3Ikh4qEqnIQxDtIhn88YKBRl/U4t++xOwGVcLxwR29hsjk3uArOoA9FniXQPAa+4CJRMAvIuAtUQUcTwGdYQ3tyJ5QrWh2KKmq2PM+xlE/8="
#  on:
#    tags: true
#    branch: master
script:
- py.test
- pylama .
